pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - .m2
    volumes:
      - /tmp/cache:/cache

  build:
    image: maven:3-jdk-8-alpine
    environment:
#      - MAVEN_CONFIG=/cache/.m2
    commands:
      - pwd
#      - mvn -B install
      - mvn -B install -Dmaven.repo.local=.m2

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - .m2
    volumes:
      - /tmp/cache:/cache
      