version: "3.7"

services:
  drone:
    container_name: drone
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /vagrant/drone:/data
    environment:
      - DRONE_SERVER_HOST=l73x60cmkzxmoz0s04sb1w.webrelay.io
      - DRONE_SERVER_PROTO=http
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=55e372ca317c085aaafc
      - DRONE_GITHUB_CLIENT_SECRET=161c364cdc4880b760ec273f56031988f7b2d722
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_SECRET=27b4b3b58a94a4ab193aa98b9c8738a1
      - DRONE_RPC_SECRET=27b4b3b58a94a4ab193aa98b9c8738a1
      - DRONE_USER_CREATE=username:markoniemi,admin:true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true      
      - DRONE_DEBUG=true

  agent:
    container_name: agent
    image: drone/agent:1
    command: agent
    restart: always
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /vagrant/agent/cache:/cache
    environment:
      - DRONE_RPC_SERVER=http://drone
      - DRONE_SECRET=27b4b3b58a94a4ab193aa98b9c8738a1
      - DRONE_RPC_SECRET=27b4b3b58a94a4ab193aa98b9c8738a1
      - DRONE_DEBUG=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true      
      - DRONE_RUNNER_VOLUMES=/vagrant/agent/cache:/cache

  relay:
    container_name: relay
    image: webhookrelay/webhookrelayd:latest
    command:
      - --mode 
      - tunnel 
      - -t
      - drone
    restart: always
    depends_on:
      - drone
    environment: 
      - KEY=21c29105-a97b-4b25-b6f0-00d48b868c1f
      - SECRET=08byciiQlmFg
